Rails3.1: test: add "require 'shoulda/rails'" at test/test_helper.rb
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20120111-5
extra : transplant_source : %5B%08%1B%E7%00%A1%28%DD%D6%13%D2%9Dx7%C1%3A%F6OO%21